import type { Product } from "@/types/product"

export const products: Product[] = [
  // Peces
  {
    id: "1",
    name: "Pez Betta",
    category: "fish",
    price: 499.99,
    image: "/colorful-betta-fish.jpg",
    description: "Hermoso y vibrante pez Betta, perfecto para acuarios pequeños.",
    inStock: true,
  },
  {
    id: "2",
    name: "Pez Dorado",
    category: "fish",
    price: 259.99,
    image: "/orange-goldfish.jpg",
    description: "Pez dorado clásico, resistente y fácil de cuidar.",
    inStock: true,
  },
  {
    id: "3",
    name: "Tetra Neón",
    category: "fish",
    price: 79.99,
    image: "/neon-tetra-fish.jpg",
    description: "Pequeños peces coloridos en cardumen que dan vida a cualquier tanque.",
    inStock: true,
  },
  // Geckos
  {
    id: "4",
    name: "Gecko Leopardo",
    category: "gecko",
    price: 1799.99,
    image: "/leopard-gecko.png",
    description: "Gecko amigable y fácil de manejar, ideal para principiantes.",
    inStock: true,
  },
  {
    id: "5",
    name: "Gecko Crestado",
    category: "gecko",
    price: 1599.99,
    image: "/crested-gecko.png",
    description: "Gecko arbóreo con apariencia única y temperamento gentil.",
    inStock: true,
  },
  // Tortugas
  {
    id: "19",
    name: "Tortuga de Orejas Rojas",
    category: "turtle",
    price: 899.99,
    image: "/red-eared-slider.jpg",
    description: "Tortuga acuática popular, perfecta para principiantes.",
    inStock: true,
  },
  {
    id: "20",
    name: "Tortuga Terrestre Rusa",
    category: "turtle",
    price: 2499.99,
    image: "/russian-tortoise.jpg",
    description: "Tortuga terrestre de tamaño mediano, muy resistente y longeva.",
    inStock: true,
  },
  // Serpientes
  {
    id: "6",
    name: "Serpiente del Maíz",
    category: "snake",
    price: 2599.99,
    image: "/corn-snake.jpg",
    description: "Serpiente dócil y colorida, perfecta para dueños primerizos.",
    inStock: true,
  },
  {
    id: "7",
    name: "Pitón Bola",
    category: "snake",
    price: 2999.99,
    image: "/ball-python.jpg",
    description: "Gentil y fácil de cuidar, una de las serpientes mascotas más populares.",
    inStock: true,
  },
  // Acuarios
  {
    id: "8",
    name: "Acuario 75 Litros",
    category: "aquarium",
    price: 1799.99,
    image: "/glass-aquarium-tank.jpg",
    description: "Acuario inicial perfecto con vidrio cristalino.",
    inStock: true,
  },
  {
    id: "9",
    name: "Acuario 200 Litros",
    category: "aquarium",
    price: 3999.99,
    image: "/large-aquarium-tank.jpg",
    description: "Acuario espacioso para colecciones grandes de peces.",
    inStock: true,
  },
  // Terrarios
  {
    id: "10",
    name: "Terrario 75 Litros",
    category: "terrarium",
    price: 2399.99,
    image: "/glass-terrarium.jpg",
    description: "Hábitat ideal para geckos y reptiles pequeños.",
    inStock: true,
  },
  {
    id: "11",
    name: "Terrario 150 Litros",
    category: "terrarium",
    price: 4999.99,
    image: "/large-reptile-terrarium.jpg",
    description: "Terrario espacioso con puertas frontales de apertura.",
    inStock: true,
  },
  // Alimento
  {
    id: "12",
    name: "Hojuelas para Peces",
    category: "food",
    price: 179.99,
    image: "/fish-food-flakes.jpg",
    description: "Hojuelas nutritivas para peces tropicales.",
    inStock: true,
  },
  {
    id: "13",
    name: "Dieta para Gecko",
    category: "food",
    price: 299.99,
    image: "/gecko-food-powder.jpg",
    description: "Polvo de reemplazo de comida completa para geckos crestados.",
    inStock: true,
  },
  {
    id: "14",
    name: "Ratones Congelados",
    category: "food",
    price: 399.99,
    image: "/frozen-feeder-mice.jpg",
    description: "Ratones alimentadores congelados para serpientes (paquete de 10).",
    inStock: true,
  },
  // Accesorios
  {
    id: "15",
    name: "Filtro para Acuario",
    category: "accessory",
    price: 699.99,
    image: "/aquarium-filter.png",
    description: "Sistema de filtración eficiente para agua limpia y saludable.",
    inStock: true,
  },
  {
    id: "16",
    name: "Lámpara de Calor",
    category: "accessory",
    price: 599.99,
    image: "/reptile-heat-lamp.jpg",
    description: "Calefacción esencial para terrarios de reptiles.",
    inStock: true,
  },
  {
    id: "17",
    name: "Decoraciones para Acuario",
    category: "accessory",
    price: 259.99,
    image: "/aquarium-decorations.jpg",
    description: "Hermosas decoraciones para mejorar tu acuario.",
    inStock: true,
  },
  {
    id: "18",
    name: "Sustrato para Reptiles",
    category: "accessory",
    price: 339.99,
    image: "/reptile-substrate.jpg",
    description: "Sustrato natural para el piso del terrario.",
    inStock: true,
  },
]
